# Generated by Django 3.1.3 on 2021-01-18 13:21

import cs28.models.graduation_year
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicPlan',
            fields=[
                ('planCode', models.CharField(help_text='The plan code that contains a letter and 3 numbers, e.g F100-2208. This field cannot be updated.', max_length=9, primary_key=True, serialize=False, verbose_name='Academic plan code')),
                ('courseCode', models.CharField(help_text='The simple degree code used in Chemistry, e.g CHEM-4H', max_length=15, verbose_name='Internal course code')),
                ('mcName', models.CharField(help_text='How MyCampus describes the plan code, e.g Chemistry. Bsc', max_length=35, verbose_name='MyCampus description')),
                ('course_1', models.CharField(blank=True, help_text="Enter the name each course name in the Course fields. One course can't exist without its weight and vice versa. Note: changes to the course names will cascade to student's module marks.", max_length=10, null=True)),
                ('weight_1', models.DecimalField(blank=True, decimal_places=3, help_text='Enter the corresponding weight of the course with the same number. Weight can only be between 0 and 1', max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('course_2', models.CharField(blank=True, max_length=10, null=True)),
                ('weight_2', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('course_3', models.CharField(blank=True, max_length=10, null=True)),
                ('weight_3', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('course_4', models.CharField(blank=True, max_length=10, null=True)),
                ('weight_4', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('course_5', models.CharField(blank=True, max_length=10, null=True)),
                ('weight_5', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('course_6', models.CharField(blank=True, max_length=10, null=True)),
                ('weight_6', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('course_7', models.CharField(blank=True, max_length=10, null=True)),
                ('weight_7', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('course_8', models.CharField(blank=True, max_length=10, null=True)),
                ('weight_8', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('course_9', models.CharField(blank=True, max_length=10, null=True)),
                ('weight_9', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('course_10', models.CharField(blank=True, max_length=10, null=True)),
                ('weight_10', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('course_11', models.CharField(blank=True, max_length=10, null=True)),
                ('weight_11', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('course_12', models.CharField(blank=True, max_length=10, null=True)),
                ('weight_12', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('course_13', models.CharField(blank=True, max_length=10, null=True)),
                ('weight_13', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('course_14', models.CharField(blank=True, max_length=10, null=True)),
                ('weight_14', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('course_15', models.CharField(blank=True, max_length=10, null=True)),
                ('weight_15', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('course_16', models.CharField(blank=True, max_length=10, null=True)),
                ('weight_16', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('course_17', models.CharField(blank=True, max_length=10, null=True)),
                ('weight_17', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('course_18', models.CharField(blank=True, max_length=10, null=True)),
                ('weight_18', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('course_19', models.CharField(blank=True, max_length=10, null=True)),
                ('weight_19', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('course_20', models.CharField(blank=True, max_length=10, null=True)),
                ('weight_20', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('course_21', models.CharField(blank=True, max_length=10, null=True)),
                ('weight_21', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('course_22', models.CharField(blank=True, max_length=10, null=True)),
                ('weight_22', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('course_23', models.CharField(blank=True, max_length=10, null=True)),
                ('weight_23', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('course_24', models.CharField(blank=True, max_length=10, null=True)),
                ('weight_24', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('course_25', models.CharField(blank=True, max_length=10, null=True)),
                ('weight_25', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('course_26', models.CharField(blank=True, max_length=10, null=True)),
                ('weight_26', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('course_27', models.CharField(blank=True, max_length=10, null=True)),
                ('weight_27', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('course_28', models.CharField(blank=True, max_length=10, null=True)),
                ('weight_28', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('course_29', models.CharField(blank=True, max_length=10, null=True)),
                ('weight_29', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('course_30', models.CharField(blank=True, max_length=10, null=True)),
                ('weight_30', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('course_31', models.CharField(blank=True, max_length=10, null=True)),
                ('weight_31', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('course_32', models.CharField(blank=True, max_length=10, null=True)),
                ('weight_32', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('course_33', models.CharField(blank=True, max_length=10, null=True)),
                ('weight_33', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('course_34', models.CharField(blank=True, max_length=10, null=True)),
                ('weight_34', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('course_35', models.CharField(blank=True, max_length=10, null=True)),
                ('weight_35', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('course_36', models.CharField(blank=True, max_length=10, null=True)),
                ('weight_36', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('course_37', models.CharField(blank=True, max_length=10, null=True)),
                ('weight_37', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('course_38', models.CharField(blank=True, max_length=10, null=True)),
                ('weight_38', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('course_39', models.CharField(blank=True, max_length=10, null=True)),
                ('weight_39', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('course_40', models.CharField(blank=True, max_length=10, null=True)),
                ('weight_40', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
            ],
            options={
                'verbose_name_plural': 'Academic Plans',
            },
        ),
        migrations.CreateModel(
            name='GraduationYear',
            fields=[
                ('gradYear', models.CharField(max_length=5, primary_key=True, serialize=False, validators=[cs28.models.graduation_year.grad_year_validator], verbose_name='Graduation Year')),
            ],
            options={
                'verbose_name_plural': 'Graduation Years',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('matricNo', models.CharField(help_text='Must be 7 digits and entirely numeric', max_length=7, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(7), django.core.validators.RegexValidator('^[0-9]*$', code='Invalid Matric No', message='Student Matric No must be a Number')], verbose_name='Matriculation number')),
                ('givenNames', models.CharField(help_text='Comma separated', max_length=64, verbose_name='Given name(s)')),
                ('surname', models.CharField(max_length=32, verbose_name='Surname')),
                ('finalAward1', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Final award (1dp)')),
                ('finalAward2', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Final award (2dp)')),
                ('finalAward3', models.DecimalField(decimal_places=3, default=0.0, max_digits=5, null=True, verbose_name='Final award (3dp)')),
                ('finalAward4', models.DecimalField(blank=True, decimal_places=4, help_text='Updating this field automatically sets Final award (1dp) and Final award (2dp). This is done to prevent rounding errors.', max_digits=6, null=True, verbose_name='Final award (4dp)')),
                ('gradeDataUpdated', models.BooleanField(default=False)),
                ('updatedAward', models.CharField(blank=True, default='-1', max_length=5, verbose_name='Updated Award')),
                ('hasSpecialCode', models.BooleanField(default=False, help_text='If this is checked, at least one grade for this student is of MV, CR or CW')),
                ('isMissingGrades', models.BooleanField(default=True, help_text='If this is checked, at least one grade for this student is missing')),
                ('academicPlan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cs28.academicplan', verbose_name='Academic plan')),
                ('gradYear', models.ForeignKey(db_column='gradYear', on_delete=django.db.models.deletion.CASCADE, to='cs28.graduationyear', verbose_name='Graduation year')),
            ],
            options={
                'verbose_name_plural': 'Students',
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseCode', models.CharField(max_length=30, verbose_name='Course Code')),
                ('alphanum', models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('A3', 'A3'), ('A4', 'A4'), ('A5', 'A5'), ('B1', 'B1'), ('B2', 'B2'), ('B3', 'B3'), ('C1', 'C1'), ('C2', 'C2'), ('C3', 'C3'), ('D1', 'D1'), ('D2', 'D2'), ('D3', 'D3'), ('E1', 'E1'), ('E2', 'E2'), ('E3', 'E3'), ('F1', 'F1'), ('F2', 'F2'), ('F3', 'F3'), ('G1', 'G1'), ('G2', 'G2'), ('H', 'H'), ('CW', 'CW'), ('CR', 'CR'), ('MV', 'MV')], max_length=2, verbose_name='Alphanumeric Grade')),
                ('matricNo', models.ForeignKey(db_column='matricNo', on_delete=django.db.models.deletion.CASCADE, to='cs28.student')),
            ],
            options={
                'verbose_name_plural': 'Grades',
            },
        ),
        migrations.AddField(
            model_name='academicplan',
            name='gradYear',
            field=models.ForeignKey(db_column='gradYear', help_text='Select one of the existing graduation years', on_delete=django.db.models.deletion.CASCADE, to='cs28.graduationyear', verbose_name='Graduation year'),
        ),
        migrations.AddConstraint(
            model_name='grade',
            constraint=models.UniqueConstraint(fields=('courseCode', 'matricNo'), name='composite_key'),
        ),
        migrations.AddConstraint(
            model_name='academicplan',
            constraint=models.UniqueConstraint(fields=('gradYear', 'planCode'), name='temp'),
        ),
    ]
